
services:
  app:
    build:
      context: .
      dockerfile: Docker/Dockerfile
    container_name: {{ _package_name }}_app
    env_file:
      - ./.env
    environment:
      ENV: development             # Override if needed
      PYTHONUNBUFFERED: 1
      PYTHONPATH: /app/src:/app/shared/src
    volumes:
      - ./src:/app/src:cached
      - ./shared/src:/app/shared/src:cached
    command: uv run main           # Default UV entrypoint
    ports:
      - "8000:8000"                # Optional: only if app exposes API
    restart: unless-stopped
    user: "1000:1000"              # Ensure non-root
